# Generated by Django 3.1.4 on 2020-12-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbooks',
            name='search',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='fbooks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbooks_FRK', to='Fbooks.fbooks'),
        ),
    ]
